### ISSUE TITLE
Error: bagian login

### ISSUE THREAD

**Issue by Ariska138** [MNadhifAttamimi/portal-siswa-by-nadhif#1]
- [x] link pada halaman login yg mengarah ke pendaftaran tidak valid/tidak bisa
- [x] link pada halaman pendaftaran yg mengarah ke login tidak valid
- [x] #2
- [x] Pada Api Login jangan menggunakan bcrypt ketika password blm di encripsi terlebih dahulu (menyebabkan error, user tidak dikenali)

**Comment by MNadhifAttamimi** [comment]
error pada bagian ketika ingin login tetapi tdk ada coneccting ke mongo db

**Comment by Ariska138** [comment]
mantap
