### ISSUE TITLE
pada API Login tidak ada koneksi ke DB

### ISSUE THREAD

**Issue by MNadhifAttamimi** [MNadhifAttamimi/portal-siswa-by-nadhif#2]

**Comment by Ariska138** [comment]
sip

**Comment by MNadhifAttamimi** [comment]
![Uploading Rekaman layar untuk tugas.gif…]()

**Comment by MNadhifAttamimi** [comment]
![Rekaman layar untuk tugas](https://github.com/MNadhifAttamimi/portal-siswa-by-nadhif/assets/114051592/87e022c9-90dc-47c9-8887-4ca01d3b3622)
