### ISSUE TITLE
Tidak ada informasi yg jelas di dasboard

### ISSUE THREAD

**Issue by Ariska138** [MNadhifAttamimi/portal-siswa-by-nadhif#4]
Ketika buka halaman dashboard muncul:
![image](https://github.com/MNadhifAttamimi/portal-siswa-by-nadhif/assets/1137972/60e4eb08-c24e-44ab-9c4b-ee97258846fb)

silakan lengkapi

- [x] tambahkan role (admin atau santri/siswa) disamping nama
- [x] tampilkan list siswa/santri ketika login sebagai admin
- [x] tidak ada list siswa/santri ketika login sebagai santri/siswa
- [x] ketika sudah berhasil login, tidak perlu ada menu sign in

**Comment by MNadhifAttamimi** [comment]
@Ariska138 
![Rekaman layar untuk tugas](https://github.com/MNadhifAttamimi/portal-siswa-by-nadhif/assets/114051592/a75e2df6-176a-46f8-8bc6-94315833016f)

**Comment by MNadhifAttamimi** [comment]
keluar list apabila dia admin

**Comment by Ariska138** [comment]
sip
